### ISSUE TITLE
macOS Sonoma intel pygdal==3.7.2.12 install fails with no such file or directory: 'extensions/gdal_wrap.cpp'

### ISSUE THREAD

**Issue by joaoluis-pdm** [nextgis/pygdal#86]
Hello! Is pygdal supposed to work on macOS with brew GDAL 3.7.2 ?

Sorry to contact you this way, but I could not figure out another way (stackoverflow ?). (Feel free to reject the issue, but please point me in some other direction if possible).

I was trying to run some python code on macOS that depends on pygdal. And I found the following issue during installation:

(macOS 14 Sonoma intel. xcode 15.0 and brew already installed. No other extra brew packages installed. Using bash.).

```sh
$ brew install python3
# ... installs python3.11.6
$ python3 -m ensurepip
#...
#Requirement already satisfied: setuptools in /usr/local/lib/python3.11/site-packages (68.2.2)
#Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (23.2.1)
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ python -m pip install --upgrade pip
# ... Successfully installed pip-23.3
(venv) $ brew install gdal
# lots of downloads, but no errors.
(venv) $ gdalinfo --version
GDAL 3.7.2, released 2023/09/05
(venv) $ pip install pygdal
Collecting pygdal
  Using cached pygdal-3.7.2.12.tar.gz (5.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.0.0 (from pygdal)
  Using cached numpy-1.26.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.1-cp311-cp311-macosx_10_9_x86_64.whl (20.6 MB)
Building wheels for collected packages: pygdal
  Building wheel for pygdal (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pygdal (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14-x86_64-cpython-311
      creating build/lib.macosx-14-x86_64-cpython-311/osgeo
      copying ./osgeo/__init__.py -> build/lib.macosx-14-x86_64-cpython-311/osgeo
      copying ./osgeo/gdalnumeric.py -> build/lib.macosx-14-x86_64-cpython-311/osgeo
      running egg_info
      writing pygdal.egg-info/PKG-INFO
      writing dependency_links to pygdal.egg-info/dependency_links.txt
      writing requirements to pygdal.egg-info/requires.txt
      writing top-level names to pygdal.egg-info/top_level.txt
      reading manifest file 'pygdal.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.py' under directory 'py2'
      warning: no files found matching '*.py' under directory 'py3'
      writing manifest file 'pygdal.egg-info/SOURCES.txt'
      running build_ext
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/jpsl/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/private/var/folders/8w/vlkt0qld4sq2w1vhx5_4_ck80000gp/T/pip-build-env-f5gnmvad/normal/lib/python3.11/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/3.7.2_1/include/gdal -I/usr/local/Cellar/gdal/3.7.2_1/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/jpsl/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/private/var/folders/8w/vlkt0qld4sq2w1vhx5_4_ck80000gp/T/pip-build-env-f5gnmvad/normal/lib/python3.11/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/3.7.2_1/include/gdal -I/usr/local/Cellar/gdal/3.7.2_1/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o -std=c++11
      building 'osgeo._gdal' extension
      creating build/temp.macosx-14-x86_64-cpython-311
      creating build/temp.macosx-14-x86_64-cpython-311/extensions
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/jpsl/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/private/var/folders/8w/vlkt0qld4sq2w1vhx5_4_ck80000gp/T/pip-build-env-f5gnmvad/normal/lib/python3.11/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/3.7.2_1/include/gdal -I/usr/local/Cellar/gdal/3.7.2_1/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-14-x86_64-cpython-311/extensions/gdal_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/3.7.2_1/include
      clang: error: no such file or directory: 'extensions/gdal_wrap.cpp'
      clang: error: no input files
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygdal
Failed to build pygdal
ERROR: Could not build wheels for pygdal, which is required to install pyproject.toml-based projects
```

I don't know how to figure out what is going on inside the build/temp.macosx-14-x86_64-cpython-311 (did not find it).

`pip install gdal` does not break, but the python code that depends on pygdal will fail (in the absence of pygdal) with: `ImportError: cannot import name '_gdal_array' from 'osgeo'`

The code that depends on pygdal is known to work on Ubuntu 22 LTS using pygdal==3.4.1.10

Any suggestion on what to try next ?

**Comment by joaoluis-pdm** [comment]
Well, for those completely lost like me, I've managed to overcome the installation error with:
```sh
(venv) $ git clone https://github.com/nextgis/pygdal.git
(venv) $ cp -rp pygdal/3.6.4/extensions pygdal/3.7.2/
(venv) $ pip install -e pygdal/3.7.2
```
(This workaround copies - apparently missing - code from 3.6.4 to 3.7.2, without knowing if it is supposed to be compatible or not...)

But the python code I am trying to run still fails with `ImportError: cannot import name '_gdal_array' from 'osgeo'`.

**Comment by joaoluis-pdm** [comment]
We have abandoned pygdal, and are just using GDAL==3.7.2
